I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.


The label _call_aa_The_Disasters is defined twice, at
  File "game/script.rpy", line 132 and
  File "game/script.rpy", line 137.

Ren'Py Version: Ren'Py 7.2.2.491
Wed Mar 11 13:32:50 2020
